#!/bin/bash

echo "🧹 MongoDB Atlas Data Cleanup"
echo "============================="
echo ""
echo "Your cluster is at 101% capacity (515 MB / 512 MB)"
echo "Let's clean up some data to free space."
echo ""
echo "🔧 Quick Cleanup Options:"
echo ""
echo "1. MongoDB Atlas Web Interface (Easiest)"
echo "   - Go to: https://cloud.mongodb.com/"
echo "   - Navigate to your fiifi-dev cluster"
echo "   - Click 'Browse Collections'"
echo "   - Delete old/unnecessary documents"
echo ""
echo "2. MongoDB Compass (Recommended)"
echo "   - Download: https://www.mongodb.com/products/compass"
echo "   - Connect using:"
echo "     mongodb+srv://fiifi-dev-v2:y7LYAZGR5zoK16yp@fiifi-dev.h3qwt.mongodb.net/"
echo "   - Browse and delete data visually"
echo ""
echo "3. MongoDB Shell (Command Line)"
echo "   - Install MongoDB Shell"
echo "   - Connect and run cleanup commands"
echo ""
echo "4. Programmatic Cleanup (via our API)"
echo "   - We can create specific cleanup endpoints"
echo ""
echo "💡 Recommended Approach:"
echo "   Use MongoDB Compass to visually browse your data"
echo "   and identify what can be safely deleted."
echo ""
echo "Would you like me to help you with any specific approach?"
