#!/bin/bash

echo "🧹 MongoDB Atlas Data Cleanup"
echo "============================="
echo ""
echo "Your cluster is at 101% capacity (515 MB / 512 MB)"
echo "Let's clean up some data to free space."
echo ""
echo "Options to free up space:"
echo ""
echo "1. Connect via MongoDB Compass (Recommended)"
echo "   - Download MongoDB Compass"
echo "   - Connect using: mongodb+srv://fiifi-dev-v2:y7LYAZGR5zoK16yp@fiifi-dev.h3qwt.mongodb.net/"
echo "   - Browse collections and delete old/unnecessary data"
echo ""
echo "2. Connect via MongoDB Shell (mongo/mongosh)"
echo "   - Install MongoDB Shell"
echo "   - Connect and run cleanup commands"
echo ""
echo "3. Use MongoDB Atlas Web Interface"
echo "   - Go to your cluster → Browse Collections"
echo "   - Delete old documents manually"
echo ""
echo "4. Programmatic cleanup via our API"
echo "   - We can create a cleanup endpoint in our app"
echo ""
echo "Which option would you prefer?"
