#!/bin/bash

echo "🔐 MongoDB Password Reset Instructions"
echo "====================================="
echo ""
echo "Since you're using password authentication, here's how to reset:"
echo ""
echo "1. In MongoDB Atlas (your current page):"
echo "   - Click on the password field (showing 'fiifi-api')"
echo "   - Click 'Reset Password' or 'Generate Password'"
echo "   - Copy the new password"
echo ""
echo "2. Update Cloud Run with the new password:"
echo "   gcloud run services update fiifi-core-api-dev \\"
echo "     --region=us-east1 \\"
echo "     --set-env-vars=MONGODB_URI='mongodb+srv://fiifi-api:NEW_PASSWORD@fiifi-dev.h3qwt.mongodb.net/?retryWrites=true&w=majority&appName=fiifi-dev'"
echo ""
echo "3. Test the connection:"
echo "   curl https://fiifi-core-api-dev-119659061108.us-east1.run.app/companies"
echo ""
echo "Alternative: If you know the current password, just use it directly"
echo "in the command above instead of resetting."
