#!/bin/bash

echo "🔗 MongoDB Atlas Connection Setup"
echo "================================="
echo ""
echo "To connect your Fiifi app to MongoDB Atlas:"
echo ""
echo "1. Go to your MongoDB Atlas dashboard"
echo "2. Click 'Connect' on your 'fiifi-dev' cluster"
echo "3. Choose 'Connect your application'"
echo "4. Copy the connection string (it looks like:)"
echo "   mongodb+srv://<username>:<password>@fiifi-dev.xxxxx.mongodb.net/?retryWrites=true&w=majority"
echo ""
echo "5. Run this command with your connection string:"
echo "   gcloud run services update fiifi-core-api-dev \\"
echo "     --region=us-east1 \\"
echo "     --set-env-vars=MONGODB_URI='your-connection-string-here'"
echo ""
echo "6. Test the connection:"
echo "   curl https://fiifi-core-api-dev-119659061108.us-east1.run.app/companies"
echo ""
echo "Note: Replace <username> and <password> with your actual credentials"
echo "      Make sure your IP is whitelisted in MongoDB Atlas Network Access"
