#!/bin/bash

echo "🔐 MongoDB Password Update"
echo "========================="
echo ""
echo "To fix the MongoDB connection:"
echo ""
echo "1. Get your actual password from MongoDB Atlas:"
echo "   - Go to Database Access → fiifi-api user"
echo "   - Copy the password (or reset it)"
echo ""
echo "2. Run this command with your REAL password:"
echo "   gcloud run services update fiifi-core-api-dev \\"
echo "     --region=us-east1 \\"
echo "     --set-env-vars=MONGODB_URI='mongodb+srv://fiifi-api:YOUR_REAL_PASSWORD@fiifi-dev.h3qwt.mongodb.net/?retryWrites=true&w=majority&appName=fiifi-dev'"
echo ""
echo "3. Test the connection:"
echo "   curl https://fiifi-core-api-dev-119659061108.us-east1.run.app/companies"
echo ""
echo "Note: Replace YOUR_REAL_PASSWORD with the actual password from MongoDB Atlas"
